# Generated by Django 4.2.5 on 2024-09-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.BigIntegerField()),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('sender', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=18, max_digits=20)),
                ('pubkey', models.CharField(blank=True, max_length=98, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
